name: Test action
on:   
  push

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: fetch resource translation repo
      run: |
        ls
