name: Update
on:   
  push:
  schedule:
    - cron: '30 9,21 * * *'

jobs:
  Update-config-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Fetch resource
      env:
        IDOL_INFO_URL: https://raw.githubusercontent.com/biuuu/shiny-image/master/idol-info.json
        ICON_URL: https://raw.githubusercontent.com/biuuu/shiny-image/master/icon-info.json
        TRANSLATION_REPO: https://github.com/ShinyGroup/SCTranslationData.git
      run: |
        git clone $TRANSLATION_REPO
        cd idol
        wget $IDOL_INFO_URL -O idol-info.json
        wget $ICON_URL -O icon-info.json
        cd ..
    
    - name: Process story tree
      run: |
        python scripts/getTree.py
    - name: Process idol info
      run: |
        python scripts/processIdolInfo.py
    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        message: update info
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com

