name: Update
on: push

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        path: repoMaster
    - name: checkout translation repo
      env:
        IDOL_INFO_URL: https://raw.githubusercontent.com/biuuu/shiny-image/master/idol-info.json
        TRANSLATION_REPO: https://github.com/ShinyGroup/SCTranslationData.git
      run: |
        git clone $TRANSLATION_REPO
    
    - name: list checkout
      run: |
        ls SCTranslationData/
    - name: get story tree
      run: |
        python scripts/getTree.py
    - name: list dir
      run: |
        ls
    - name: copy and commit
      run: |
        cp ./story_tree.json repoMaster/story_tree.json
        cd repoMaster
        git add .
        git commit -m "update story tree"
        git push origin main
