name: Update
on: push

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        path: repoMaster
    - name: fetch resource translation repo
      env:
        IDOL_INFO_URL: https://raw.githubusercontent.com/biuuu/shiny-image/master/idol-info.json
        TRANSLATION_REPO: https://github.com/ShinyGroup/SCTranslationData.git
      run: |
        git clone $TRANSLATION_REPO
        wget $IDOL_INFO_URL
    
    - name: get story tree
      run: |
        python repoMaster/scripts/getTree.py
    - name: list dir
      run: |
        ls
    - name: copy and commit
      run: |
        cp ./idol-info.json repoMaster/idol-info.json
        cp ./story-tree.json repoMaster/story-tree.json
        git config --global user.email "daerwendeshu@outlook.com"
        git config --global user.name "七草葉月"
        cd repoMaster
        git add .
        git commit -m "update story tree"
        git push origin main
