name: Update
on: push

jobs:
  index:
    name: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout translation repo
      env:
        IDOL_INFO_URL: https://raw.githubusercontent.com/biuuu/shiny-image/master/idol-info.json
        TRANSLATION_REPO: https://github.com/ShinyGroup/SCTranslationData.git
      run: |
        git clone $TRANSLATION_REPO
    
    - name: list checkout
      run: |
        ls SCTranslationData/